apiVersion: v1
kind: Pod
spec:
  containers:
    - name: cloudsql-proxy
      env:
        - name: DB_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: pexapark-common-config
              key: db_connection_name
      image: gcr.io/cloudsql-docker/gce-proxy:1.11
      command: ["/cloud_sql_proxy"]
      args: ["-instances=$(DB_CONNECTION_NAME)=tcp:5432", "-credential_file=/secrets/cloudsql/credentials.json"]
      volumeMounts:
        - name: secrets-volume
          mountPath: /secrets/cloudsql
          readOnly: true
    - name: node
      image: node:6
      tty: true
      env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_name
  volumes:
    - name: secrets-volume
      secret:
        secretName: cloudsql-instance-credentials
